import { LLMFlags, LLMFormat, LLMProvider, LLMTokenizer, ClaudeParameters, OpenAIParameters, GPT5Parameters, type LLMModel } from '../types'

export const CopilotModels: LLMModel[] = [

    // ── Anthropic (via Copilot) ─────────────────────────────────────

    {
        name: "Claude 4.6 Opus",
        id: 'copilot-claude-opus-4.6',
        internalID: 'claude-opus-4.6',
        shortName: "GH Copilot Opus 4.6",
        provider: LLMProvider.Copilot,
        format: LLMFormat.Anthropic,
        flags: [
            LLMFlags.hasImageInput,
            LLMFlags.hasFirstSystemPrompt,
            LLMFlags.hasStreaming,
            LLMFlags.claudeThinking,
            LLMFlags.claudeAdaptiveThinking
        ],
        parameters: [...ClaudeParameters, 'thinking_tokens'],
        tokenizer: LLMTokenizer.Claude,
        recommended: true
    },
    {
        name: "Claude 4.6 Opus (Fast)",
        id: 'copilot-claude-opus-4.6-fast',
        internalID: 'claude-opus-4.6-fast',
        shortName: "GH Copilot Opus 4.6 Fast",
        provider: LLMProvider.Copilot,
        format: LLMFormat.Anthropic,
        flags: [
            LLMFlags.hasImageInput,
            LLMFlags.hasFirstSystemPrompt,
            LLMFlags.hasStreaming,
            LLMFlags.claudeThinking,
            LLMFlags.claudeAdaptiveThinking
        ],
        parameters: [...ClaudeParameters, 'thinking_tokens'],
        tokenizer: LLMTokenizer.Claude,
    },
    {
        name: "Claude 4.6 Sonnet",
        id: 'copilot-claude-sonnet-4.6',
        internalID: 'claude-sonnet-4.6',
        shortName: "GH Copilot Sonnet 4.6",
        provider: LLMProvider.Copilot,
        format: LLMFormat.Anthropic,
        flags: [
            LLMFlags.hasImageInput,
            LLMFlags.hasFirstSystemPrompt,
            LLMFlags.hasStreaming,
            LLMFlags.claudeThinking,
            LLMFlags.claudeAdaptiveThinking
        ],
        parameters: [...ClaudeParameters, 'thinking_tokens'],
        tokenizer: LLMTokenizer.Claude,
        recommended: true
    },
    {
        name: "Claude 4.5 Opus",
        id: 'copilot-claude-opus-4.5',
        internalID: 'claude-opus-4.5',
        shortName: "GH Copilot Opus 4.5",
        provider: LLMProvider.Copilot,
        format: LLMFormat.Anthropic,
        flags: [
            LLMFlags.hasImageInput,
            LLMFlags.hasFirstSystemPrompt,
            LLMFlags.hasStreaming,
        ],
        parameters: ClaudeParameters,
        tokenizer: LLMTokenizer.Claude,
    },
    {
        name: "Claude 4.5 Sonnet",
        id: 'copilot-claude-sonnet-4.5',
        internalID: 'claude-sonnet-4.5',
        shortName: "GH Copilot Sonnet 4.5",
        provider: LLMProvider.Copilot,
        format: LLMFormat.Anthropic,
        flags: [
            LLMFlags.hasImageInput,
            LLMFlags.hasFirstSystemPrompt,
            LLMFlags.hasStreaming,
        ],
        parameters: ClaudeParameters,
        tokenizer: LLMTokenizer.Claude,
    },
    {
        name: "Claude 4.5 Haiku",
        id: 'copilot-claude-haiku-4.5',
        internalID: 'claude-haiku-4.5',
        shortName: "GH Copilot Haiku 4.5",
        provider: LLMProvider.Copilot,
        format: LLMFormat.Anthropic,
        flags: [
            LLMFlags.hasImageInput,
            LLMFlags.hasFirstSystemPrompt,
            LLMFlags.hasStreaming,
        ],
        parameters: ClaudeParameters,
        tokenizer: LLMTokenizer.Claude,
    },
    {
        name: "Claude 4 Sonnet",
        id: 'copilot-claude-sonnet-4',
        internalID: 'claude-sonnet-4',
        shortName: "GH Copilot Sonnet 4",
        provider: LLMProvider.Copilot,
        format: LLMFormat.Anthropic,
        flags: [
            LLMFlags.hasImageInput,
            LLMFlags.hasFirstSystemPrompt,
            LLMFlags.hasStreaming,
        ],
        parameters: ClaudeParameters,
        tokenizer: LLMTokenizer.Claude,
    },

    // ── OpenAI (via Copilot) ────────────────────────────────────────

    {
        name: "GPT-5.4",
        id: 'copilot-gpt-5.4',
        internalID: 'gpt-5.4',
        shortName: "GH Copilot 5.4",
        provider: LLMProvider.Copilot,
        format: LLMFormat.OpenAIResponseAPI,
        flags: [
            LLMFlags.hasImageInput,
            LLMFlags.hasFullSystemPrompt,
            LLMFlags.hasStreaming,
        ],
        parameters: GPT5Parameters,
        tokenizer: LLMTokenizer.tiktokenO200Base,
        recommended: true
    },
    {
        name: "GPT-5.2",
        id: 'copilot-gpt-5.2',
        internalID: 'gpt-5.2',
        shortName: "GH Copilot 5.2",
        provider: LLMProvider.Copilot,
        format: LLMFormat.OpenAICompatible,
        flags: [
            LLMFlags.hasImageInput,
            LLMFlags.hasFullSystemPrompt,
            LLMFlags.hasStreaming,
        ],
        parameters: GPT5Parameters,
        tokenizer: LLMTokenizer.tiktokenO200Base,
    },
    {
        name: "GPT-5.1",
        id: 'copilot-gpt-5.1',
        internalID: 'gpt-5.1',
        shortName: "GH Copilot 5.1",
        provider: LLMProvider.Copilot,
        format: LLMFormat.OpenAICompatible,
        flags: [
            LLMFlags.hasImageInput,
            LLMFlags.hasFullSystemPrompt,
            LLMFlags.hasStreaming,
        ],
        parameters: GPT5Parameters,
        tokenizer: LLMTokenizer.tiktokenO200Base,
    },
    {
        name: "GPT-5 Mini",
        id: 'copilot-gpt-5-mini',
        internalID: 'gpt-5-mini',
        shortName: "GH Copilot 5 Mini",
        provider: LLMProvider.Copilot,
        format: LLMFormat.OpenAICompatible,
        flags: [
            LLMFlags.hasImageInput,
            LLMFlags.hasFullSystemPrompt,
            LLMFlags.hasStreaming,
        ],
        parameters: GPT5Parameters,
        tokenizer: LLMTokenizer.tiktokenO200Base,
    },
    {
        name: "GPT-4o",
        id: 'copilot-gpt-4o',
        internalID: 'gpt-4o',
        shortName: "GH Copilot 4o",
        provider: LLMProvider.Copilot,
        format: LLMFormat.OpenAICompatible,
        flags: [
            LLMFlags.hasImageInput,
            LLMFlags.hasFullSystemPrompt,
            LLMFlags.hasStreaming,
        ],
        parameters: OpenAIParameters,
        tokenizer: LLMTokenizer.tiktokenO200Base,
    },
    {
        name: "GPT-4.1",
        id: 'copilot-gpt-4.1',
        internalID: 'gpt-4.1',
        shortName: "GH Copilot 4.1",
        provider: LLMProvider.Copilot,
        format: LLMFormat.OpenAICompatible,
        flags: [
            LLMFlags.hasImageInput,
            LLMFlags.hasFullSystemPrompt,
            LLMFlags.hasStreaming,
        ],
        parameters: OpenAIParameters,
        tokenizer: LLMTokenizer.tiktokenO200Base,
    },

    // ── Google (via Copilot) ────────────────────────────────────────

    {
        name: "Gemini 2.5 Pro",
        id: 'copilot-gemini-2.5-pro',
        internalID: 'gemini-2.5-pro',
        shortName: "GH Copilot 2.5 Pro",
        provider: LLMProvider.Copilot,
        format: LLMFormat.OpenAICompatible,
        flags: [
            LLMFlags.hasImageInput,
            LLMFlags.hasFullSystemPrompt,
            LLMFlags.hasStreaming,
        ],
        parameters: OpenAIParameters,
        tokenizer: LLMTokenizer.GoogleCloud,
    },
    {
        name: "Gemini 3 Flash",
        id: 'copilot-gemini-3-flash-preview',
        internalID: 'gemini-3-flash-preview',
        shortName: "GH Copilot 3 Flash",
        provider: LLMProvider.Copilot,
        format: LLMFormat.OpenAICompatible,
        flags: [
            LLMFlags.hasImageInput,
            LLMFlags.hasFullSystemPrompt,
            LLMFlags.hasStreaming,
        ],
        parameters: OpenAIParameters,
        tokenizer: LLMTokenizer.GoogleCloud,
    },
    {
        name: "Gemini 3 Pro",
        id: 'copilot-gemini-3-pro-preview',
        internalID: 'gemini-3-pro-preview',
        shortName: "GH Copilot 3 Pro",
        provider: LLMProvider.Copilot,
        format: LLMFormat.OpenAICompatible,
        flags: [
            LLMFlags.hasImageInput,
            LLMFlags.hasFullSystemPrompt,
            LLMFlags.hasStreaming,
        ],
        parameters: OpenAIParameters,
        tokenizer: LLMTokenizer.GoogleCloud,
    },
    {
        name: "Gemini 3.1 Pro",
        id: 'copilot-gemini-3.1-pro-preview',
        internalID: 'gemini-3.1-pro-preview',
        shortName: "GH Copilot 3.1 Pro",
        provider: LLMProvider.Copilot,
        format: LLMFormat.OpenAICompatible,
        flags: [
            LLMFlags.hasImageInput,
            LLMFlags.hasFullSystemPrompt,
            LLMFlags.hasStreaming,
        ],
        parameters: OpenAIParameters,
        tokenizer: LLMTokenizer.GoogleCloud,
    },
]
